### ISSUE TITLE
Ryu errors

### ISSUE THREAD

**Issue by Pastello** [Kidel/Kathara#7]
I am trying to use Ryu to setup a SDN controller, but I keep getting errors whatever I do (even if I simply use --help option). Here is an example:

- From **ryu of-config-cli -h**:

```
Traceback (most recent call last):
  File "/usr/local/bin/ryu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/ryu_base.py", line 72, in main
    subcmd_mod = utils.import_module(subcmd_mod_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/utils.py", line 102, in import_module
    mod = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/of_config_cli.py", line 31, in <module>
    import lxml.etree as ET
ImportError: No module named lxml.etree
```

- From **ryu-manager -h**:
```
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:15> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:16> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:18> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:19> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:10> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:11> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:26> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:27> ignored
lzma module is not available
Registered VCS backend: git
Registered VCS backend: hg
Registered VCS backend: svn
Registered VCS backend: bzr
```

- Same for **ryu-manager /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py**

I am posting here because I think it can be a version mismatching of some modules

**Comment by Kidel** [comment]
Hi, I've assigned @glospoto to this issue, since he's our Ryu expert.

**Comment by glospoto** [comment]
Hi,
may I ask you to post the output of the following commands?
`dpkg -l | grep lzma`
and
`dpkg -l | grep lxml`
Thanks,
Gabriele

**Comment by Pastello** [comment]
Ho eseguito i comandi sia sull'host che sul guest (perché non ricordo se un container docker eredita le librerie dal sistema host). Ecco gli output:

- Esecuzione di `dpkg -l | grep lxml` sulla macchina **host**:
```
ii  python3-lxml                                                3.5.0-1build1                              amd64        pythonic binding for the libxml2 and libxslt libraries
```
- Esecuzione di `dpkg -l | grep lzma` sulla macchina **host**:
```
ii  liblzma5:amd64                                              5.1.1alpha+20120614-2ubuntu2               amd64        XZ-format compression library
```
<hr>

- Esecuzione di `dpkg -l | grep lxml` sulla macchina **guest** (docker kathara/netkit_base):
```
```
(niente)
- Esecuzione di `dpkg -l | grep lzma` sulla macchina **guest** (docker kathara/netkit_base):
```
ii  liblzma5:amd64                5.1.1alpha+20120614-2.1ubuntu1    amd64        XZ-format compression library
```

**Comment by Kidel** [comment]
Considera che oggi abbiamo aggiornato ovs (ancora non pubblicamente). 
Appena finiamo i test carichiamo l'immagine nuova.

**Comment by Kidel** [comment]
Anzi, se vuoi puoi già testarla se aggiungi questo al lab.conf:

`nomemacchina[image]=netkit_base_edit`

Se invece ti poace vstart basta aggiungere (prima del nome della macchina) `--image=netkit_base_edit`

Così puoi darci un feedback

**Comment by Pastello** [comment]
Ho scaricato la nuova immagine docker (netkit_base_edit) e ho eseguito questo comando: `ryu-manager /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py 2> /hosthome/Scrivania/erroriRyu.txt`
Il file generato contiene questi errori:
```
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:15> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:16> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:18> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:19> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:10> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:11> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:26> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:27> ignored
lzma module is not available
Registered VCS backend: git
Registered VCS backend: hg
Registered VCS backend: svn
Registered VCS backend: bzr
loading app /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py
loading app ryu.controller.ofp_handler
instantiating app /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py of SimpleSwitch
instantiating app ryu.controller.ofp_handler of OFPHandler
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:7> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:8> ignored
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 81, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 516, in instantiate_apps
    t = app.start()
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 178, in start
    self.threads.append(hub.spawn(self._event_loop))
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 68, in spawn
    return eventlet.spawn(_launch, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 50, in spawn
    hub = hubs.get_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```
Ho notato questa riga: `lzma module is not available`
Ho errori del genere per ogni esecuzione di `ryu-manager`, anche se eseguo semplicemente `ryu-manager -h`
<hr>

Non so se `ryu-manager` sia il comando giusto, però anche se eseguo `ryu run /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py` ottengo solo errori:
```
loading app /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py
loading app ryu.controller.ofp_handler
instantiating app /usr/local/lib/python2.7/dist-packages/ryu/app/simple_switch.py of SimpleSwitch
instantiating app ryu.controller.ofp_handler of OFPHandler
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:7> ignored
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:8> ignored
Traceback (most recent call last):
  File "/usr/local/bin/ryu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/ryu_base.py", line 74, in main
    subcmd.run(base_conf.subcommand_args)
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/ryu_base.py", line 57, in run
    self.entry(args=args, prog=prog)
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 81, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 516, in instantiate_apps
    t = app.start()
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 178, in start
    self.threads.append(hub.spawn(self._event_loop))
  File "/usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py", line 68, in spawn
    return eventlet.spawn(_launch, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 50, in spawn
    hub = hubs.get_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

**Comment by RinaldoBuratti** [comment]
ho avuto lo stesso problema, per risolvere esegui questo comando:
`nano usr/local/lib/python2.7/dist-packages/ryu/lib/hub.py`
sotto alla stringa `import eventlet`, aggiungi: 
`eventlet.sleep()`
@Kidel @glospoto mi sono permesso di rispondere, probabilmente esiste un modo più efficiente per risolvere (in questo modo è necessario eseguire la procedura per ogni macchina virtuale).

**Comment by glospoto** [comment]
@Pastello effettivamente mancano due librerie. All'interno del container (e non sulla macchina host), puoi eseguire questi due comandi:
`apt-get install python-lzma`
e
`apt-get install python-lxml`
Queste due installazioni dovrebbero risolvere i problemi. Tuttavia, come diceva @Kidel a breve rilasceremo una nuova versione dell'immagine.

**Comment by glospoto** [comment]
@Pastello , hai anche seguito il suggerimento di @RinaldoBuratti di aggiungere `eventlet.sleep()`?
Tuttavia, a breve rilasceremo una nuova versione dell'immagine base di Kathara che risolve tutti questi problemi.

**Comment by Pastello** [comment]
No, quello ancora no

**Comment by Kidel** [comment]
Sembra che tutto funzioni comunque (anche sulla precedente immagine).

A breve metteremo dei lab di esempio per mostrare come configurare correttamente ovs e ryu. Se vuoi puoi seguire lo stato dei lavori su questa branch: https://github.com/Kidel/Kathara/tree/SDN_examples

Quando i lab saranno pronti li metteremo su master comunque.

**Comment by glospoto** [comment]
A new images fixing the problems has been published. Update the image.
